# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 02481089caad61bbb53f8015778f31fd9956c7bfb4fab5a6ce02e00f5fb78a1966521243f14b2bb6662a807ac04d15bd7ed5f55e2abf493c091bfcc88456ee24

test:
  secret_key_base: 53c72206598158e80566aceb1ff3f98e2c518aac4dc650f4110013784f153253a1e0244f49d0711b8c8d89302ba3ce273582f923205b79e25568409a63095148

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
